apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
  labels:
    app: apache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: apache
        image: harshvardhan1402/demo-app-logs 
        ports:
        - containerPort: 80
